spring:
  redis:
    host: jenkin-study.ipugwp.ng.0001.apn2.cache.amazonaws.com
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://jenkins-study.cico25wjzfni.ap-northeast-2.rds.amazonaws.com:3306/jenkins_study?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: admin
    password: 'admin123'
  jackson:
    date-format: 'yyy-MM-dd HH:mm:ss'
    time-zone: GMT+8
